todolist/apps/todo/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('initial/', views.InitialTasksPerUserListView.as_view(), name='initial'),
    path('pending/', views.PendingTasksPerUserListView.as_view(), name='pending'),
    path('resolved/', views.ResolvedTasksPerUserListView.as_view(), name='resolved'),
    path('all/', views.AllTasksPerUserListView.as_view(), name='all'),
    path('task/(?P<pk>\d+)', views.TaskDetailView.as_view(), name='task-detail'),
    path('task/create/', views.TaskCreate.as_view(), name='task_create'),
    path('task/(?P<pk>\d+)/update/', views.TaskUpdate.as_view(), name='task_update'),
    path('task/(?P<pk>\d+)/delete/', views.TaskDelete.as_view(), name='task_delete'),
    path('test/', views.test, name = 'test'),
    path('register/', views.register, name='register')
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='todo/', permanent=True))
]

todolist/apps/todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Task(models.Model):
    task_name = models.CharField('Task name', help_text='Enter name of the task', max_length=30)
    task_description = models.TextField('Task description', help_text='Add task description', max_length=200)

    TASK_STATUS = (
        ('i', 'Initial'),
        ('p', 'Pending'),
        ('r', 'Resolved')
    )

    status = models.CharField(max_length=1, choices=TASK_STATUS, default='i', help_text='Set status of the task')

    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.task_name

    def get_absolute_url(self):
        return reverse('task-detail', args=[str(self.id)])

todolist/apps/todo/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, required=True, help_text='Required. Provide a valid email address.')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',)

todolist/apps/todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Task
from .forms import RegisterForm

def index(request):
    num_tasks = Task.objects.all().count()
    num_initial_tasks = Task.objects.filter(status__exact='i').count()
    num_pending_tasks = Task.objects.filter(status__exact='p').count()
    num_resolved_tasks = Task.objects.filter(status__exact='r').count()

    return render(
        request,
        'index.html',
        context = {
            'num_tasks': num_tasks,
            'num_initial_tasks': num_initial_tasks,
            'num_pending_tasks': num_pending_tasks,
            'num_resolved_tasks': num_resolved_tasks
        }
    )

class TaskDetailView(generic.DetailView):
    model = Task

class InitialTasksPerUserListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = 'todo/task_initial_list_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Task.objects.filter(creator=self.request.user).filter(status__exact='i')

class PendingTasksPerUserListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = 'todo/task_pending_list_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Task.objects.filter(creator=self.request.user).filter(status__exact='p')

class ResolvedTasksPerUserListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = 'todo/task_resolved_list_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Task.objects.filter(creator=self.request.user).filter(status__exact='r')

class AllTasksPerUserListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = 'todo/task_list_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Task.objects.filter(creator=self.request.user)

class TaskCreate(CreateView):
    model = Task
    fields = '__all__'
    initial = {'status': 'i', }

class TaskUpdate(UpdateView):
    model = Task
    template_name = 'todo/task_update_form.html'
    fields = ['task_name', 'task_description', 'status', 'creator']

class TaskDelete(DeleteView):
    model = Task
    success_url = reverse_lazy('index')

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            response = HttpResponse()
            response['user'] = user
            return response
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})

def test(request):
    return HttpResponse('This is test page!')

todolist/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>ToDo Website</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'initial' %}">Initial tasks</a></li>
                    <li><a href="{% url 'pending' %}">Pending tasks</a></li>
                    <li><a href="{% url 'resolved' %}">Resolved tasks</a></li>
                    <li><a href="{% url 'all' %}">All tasks</a></li>
                    <li><a href="{% url 'task_create' %}">Create task</a></li>
                    <li><a href="{% url 'logout'%}?next={{index}}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}

            {% block pagination %}
            {% if is_paginated %}
            <div class="pagination">
                      <span class="page-links">
                          {% if page_obj.has_previous %}
                              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                          {% endif %}
                          <span class="page-current">
                              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                          </span>
                          {% if page_obj.has_next %}
                              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                          {% endif %}
                      </span>
            </div>
            {% endif %}
            {% endblock %}
        </div>
    </div>

</div>
</body>
</html>

todolist/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>ToDo Website Home</h1>

<p>Welcome to <em>ToDo Website</em>, django application that provides you an opportunity to write down your tasks.
</p>

<h2>Current statistics:</h2>
<ul>
    <li><strong>Initial tasks:</strong> {{ num_initial_tasks }}</li>
    <li><strong>Pending tasks:</strong> {{ num_pending_tasks }}</li>
    <li><strong>Resolved tasks:</strong> {{ num_resolved_tasks }}</li>
    <li><strong>Tasks submitted:</strong> {{ num_tasks }}</li>

</ul>

{% endblock %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Register</button>
  </form>
{% endblock %}

todolist/templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete task</h1>

<p>Are you sure you want to delete the task: {{ task }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

todolist/templates/todo/task_detail.html
{% extends "base.html" %}

{% block sidebar %}
<ul class="sidebar-nav">
    <li><a href="{% url 'index' %}">Home</a></li>
    {% if user.is_authenticated %}
        <li>User: {{ user.get_username }}</li>
        <li><a href="{% url 'initial' %}">Initial tasks</a></li>
        <li><a href="{% url 'pending' %}">Pending tasks</a></li>
        <li><a href="{% url 'resolved' %}">Resolved tasks</a></li>
        <li><a href="{% url 'all' %}">All tasks</a></li>
        <li><a href="{% url 'task_create' %}">Create task</a></li>
        <li><a href="{% url 'task_update' pk=task.pk %}">Update task</a></li>
        <li><a href="{% url 'task_delete' pk=task.pk %}">Delete task</a></li>
        <li><a href="{% url 'logout'%}?next={{all}}">Logout</a></li>
    {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
    {% endif %}
</ul>
{% endblock %}

{% block content %}

<h1>Detailed information</h1>

<p><strong>Task name:</strong> {{ task.task_name }}</p>
<p><strong>Task description:</strong> {{ task.task_description }}</p>
<p class="{% if task.status == 'r' %}text-success{% else %}text-danger{% endif %}">
    {{ task.get_status_display }}</p>

{% endblock %}

todolist/templates/todo/task_form.html
{% extends "base.html" %}

{% block content %}

<h1>Add a task</h1>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

todolist/templates/todo/task_initial_list_user.html
{% extends "base.html" %}

{% block content %}
<h1>My initial tasks</h1>

{% if task_list %}
<ul>
    {% for task in task_list %}
    <li>
        <a href="{{ task.get_absolute_url }}">{{task.task_name}}</a>
    </li>
    {% endfor %}
</ul>

{% else %}
<p>I don't have any initial tasks.</p>
{% endif %}
{% endblock %}

todolist/templates/todo/task_list_user.html
{% extends "base.html" %}

{% block content %}
<h1>My tasks</h1>

{% if task_list %}
<ul>
    {% for task in task_list %}
    <li>
        <a href="{{ task.get_absolute_url }}">{{task.task_name}}</a>
    </li>
    {% endfor %}
</ul>

{% else %}
<p>I don't have any tasks.</p>
{% endif %}
{% endblock %}

todolist/templates/todo/task_pending_list_user.html
{% extends "base.html" %}

{% block content %}
<h1>My pending tasks</h1>

{% if task_list %}
<ul>
    {% for task in task_list %}
    <li>
        <a href="{{ task.get_absolute_url }}">{{task.task_name}}</a>
    </li>
    {% endfor %}
</ul>

{% else %}
<p>I don't have any pending tasks.</p>
{% endif %}
{% endblock %}

todolist/templates/todo/task_resolved_list_user.html
{% extends "base.html" %}

{% block content %}
<h1>My resolved tasks</h1>

{% if task_list %}
<ul>
    {% for task in task_list %}
    <li>
        <a href="{{ task.get_absolute_url }}">{{task.task_name}}</a>
    </li>
    {% endfor %}
</ul>

{% else %}
<p>I don't have any resolved tasks.</p>
{% endif %}
{% endblock %}

todolist/templates/todo/task_update_form.html
{% extends "base.html" %}

{% block content %}

<h1>Update a task</h1>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}